apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: items.philbrookes
spec:
  group: philbrookes
  names:
    kind: Item
    listKind: ItemList
    plural: items
    singular: item
  scope: Namespaced
  version: finalizer
