apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalizer-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: finalizer-operator
  template:
    metadata:
      labels:
        name: finalizer-operator
    spec:
      containers:
        - name: finalizer-operator
          image: quay.io/philbrookes/finalizer-operator:0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - finalizer-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "finalizer-operator"
